### ISSUE TITLE
Cant't reach install.php

### ISSUE THREAD

**Issue by WWWorksnl** [roadiz/roadiz#296]
Trying for weeks now. Works on localhost with WAMP. But not on my VPS running CentOS 7 with Plesk. I get this on my page "You are not allowed to access this file (94.--.--.221). Check install.php for more information." When I add my IP address (94.--.--.221) to install.php, I get a blank page.
This is how my install.php looks like:
$allowedIp = [
    '10.0.2.2',     // vagrant host (forwarded)
    '192.168.33.1', // vagrant host (private)
     //'172.21.0.1', // docker host (FOR DEV ONLY)
    '127.0.0.1', 'fe80::1', '::1', ':ffff:127.0.0.1', '::ffff:127.0.0.1' // localhost
	'94.---.---.221' // home
];
Can't I leave the whole IP thing out? If yes, how?
I put the --- between my IP because of privacy/security

**Comment by WWWorksnl** [comment]
I put the --- between my IP because of privacy/security

**Comment by jakesullyneytiri** [comment]
I did same but i has to replace 10.0.2.2 with my ip then it worked. I couldn't add my own ip to file since doing it would just cause a php error.

**Comment by ambroisemaupate** [comment]
@WWWorksnl  install.php should not be used on a production environment! If you really need to, add your WAN IP address to the install.php and follow instructions.

If you see a blank page, that’s because you have an error, you can enable `display_error` flag in your PHP configuration or just look at your logs to see what is the issue. Did you install all needed PHP extensions (http://docs.roadiz.io/en/latest/developer/first-steps/requirements.html)?

---

If you have a local WAMP environment you should just dump your database and your files and copy them to your VPS

http://docs.roadiz.io/en/latest/developer/first-steps/moving.html#moving-to-a-ssh-git-hosting-plan-or-an-other-development-machine

`bin/roadiz database:dump -c` and `bin/roadiz files:export` will generate all the files you need to move your local environment to production. Then import your MySQL dump and your file in your VPS then call `bin/roadiz generate:nsentities` to recreate Node-types classes on your VPS from your database.

**Comment by ambroisemaupate** [comment]
Closing issue, if needed reopen your issue on https://ask.roadiz.io/
